version = 1

test_patterns = ["app/backend/src/tests"]

exclude_patterns = [
  "migrations",
  "models",
  "seeders"
]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]